# Crear un alumno
POST http://localhost:8080/alumno/
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Pérez",
    "dni": 12345678
}

###

# Crear un Profesor
POST http://localhost:8080/profesor/
Content-Type: application/json

{
    "nombre": "Pedro",
    "apellido": "Garcia",
    "titulo": "Licenciado en Computación"
}

###

# Buscar un profesor por apellido
GET http://localhost:8080/profesor?apellido=Garcia

###

# Buscar un profesor por id
GET http://localhost:8080/profesor/

###

# Actualizar un profesor
PUT http://localhost:8080/profesor/520
Content-Type: application/json

{
    "nombre": "Luciano",
    "apellido": "Cossia",
    "titulo": "Abogado"
}

###

# Crear una materia
POST http://localhost:8080/materia/
Content-Type: application/json

{
    "nombre": "ProgramacionI",
    "anio": 1,
    "cuatrimestre": 1,
    "profesorId": 520,
    "correlatividades": []
}

###

# Buscar una materia por nombre
GET http://localhost:8080/materia?nombre=ProgramacionI

###

# Buscar una materia por id
GET http://localhost:8080/materia/35
