# Crear un alumno
POST http://localhost:8080/alumno/
Content-Type: application/json

{
    "nombre": "Carlos",
    "apellido": "Rodriguez",
    "dni": 12345678
}

###

# Buscar un alumno por apellido
GET http://localhost:8080/alumno?apellido=Rodriguez

###

# Buscar un alumno por id
GET http://localhost:8080/alumno?id=1955834714492803438

###

# Buscar un alumno por dni
GET http://localhost:8080/alumno?dni=12345678

###

# Actualizar un alumno
PUT http://localhost:8080/alumno/5753863295338116865
Content-Type: application/json

{
    "nombre": "Carlos",
    "apellido": "Rodriguez",
    "dni": 87654321
}

# Crear un Profesor
POST http://localhost:8080/profesor/
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Sanchez",
    "titulo": "Licenciado en Computación"
}

###
POST http://localhost:8080/profesor/
Content-Type: application/json

{
    "nombre": "Pedro",
    "apellido": "Perez",
    "titulo": "Licenciado en Computación"
}

###

# Obtener todos los profesores
GET http://localhost:8080/profesor

###

# Buscar un profesor por apellido
GET http://localhost:8080/profesor?apellido=Perez

###

# Buscar un profesor por id
GET http://localhost:8080/profesor?idProfesor=980

###

# Actualizar un profesor
PUT http://localhost:8080/profesor/580
Content-Type: application/json

{
    "nombre": "Luciano",
    "apellido": "Cossia",
    "titulo": "Tecnico Universitario en Programacion"
}

###

# Obtener las materias de un profesor
GET http://localhost:8080/profesor/360/materias

###

# Borrar un profesor por id
DELETE http://localhost:8080/profesor/94

###

# Crear una materia
POST http://localhost:8080/materia/
Content-Type: application/json

{
    "nombre": "ProgramacionI",
    "anio": 1,
    "cuatrimestre": 1,
    "profesorId": 360,
    "correlatividades": []
}

### 

POST http://localhost:8080/materia/
Content-Type: application/json

{
    "nombre": "ProgramacionII",
    "anio": 1,
    "cuatrimestre": 1,
    "profesorId": 13,
    "correlatividades": [960]
}

###

# Buscar una materia por nombre
GET http://localhost:8080/materia?nombre=ProgramacionI

###

# Buscar una materia por id
GET http://localhost:8080/materia/960
